Update bash

diff --git a/config/bash/functions b/config/bash/functions
--- a/config/bash/functions
+++ b/config/bash/functions
@@ -53,19 +53,19 @@ ex() {
   fi
 
   case $1 in
-    *.7z) 7z x $1       ;;
-    *.bz2) bunzip2 $1   ;;
-    *.deb) ar x $1      ;;
-    *.gz) gunzip $1     ;;
-    *.rar) unrar x $1   ;;
-    *.tar) tar xf $1    ;;
+    *.7z  ) 7z x $1       ;;
+    *.bz2 ) bunzip2 $1   ;;
+    *.deb ) ar x $1      ;;
+    *.gz  ) gunzip $1     ;;
+    *.rar ) unrar x $1   ;;
+    *.tar ) tar xf $1    ;;
     *.tbz2) tar xjf $1  ;;
-    *.tgz) tar xzf $1   ;;
-    *.xz) tar xf $1     ;;
-    *.zip) unzip $1     ;;
-    *.zst) unzstd $1    ;;
-    *.Z) uncompress $1 ;;
-    *) echo "error: '$1' cannot be extracted" >&2 ;;
+    *.tgz ) tar xzf $1   ;;
+    *.xz  ) tar xf $1     ;;
+    *.zip ) unzip $1     ;;
+    *.zst ) unzstd $1    ;;
+    *.Z   ) uncompress $1 ;;
+    *     ) echo "error: '$1' cannot be extracted" >&2 ;;
   esac
 }
 
@@ -164,7 +164,7 @@ mkcd() {
   if [[ -n $1 ]]; then
     mkdir -p "$1" && cd "$1"
   else
-    echo "error: dirname not exist" >&2
+    echo 'error: dirname not exist' >&2
     return 1
   fi
 }
@@ -180,10 +180,8 @@ mkdia() {
 # Create shell file
 mksh() {
   local file="$1"
-
-  [[ -z "$file" ]] && { echo "error: need a name for script" >&2 && return 1; }
-  [[ -e "$file" ]] && { echo "error: file already exist" >&2 && return 1; }
-
+  [[ -z "$file" ]] && { echo 'error: need a name for script' >&2 && return 1; }
+  [[ -e "$file" ]] && { echo 'error: file already exist' >&2 && return 1; }
   echo -e "#!/usr/bin/env bash\n\n" > "$file"
   chmod +x "$file" && $EDITOR +3 "$file"
 }
@@ -242,11 +240,13 @@ mvd() {
     echo 'usage: mvd <char-duplicate>' >&2
     return 1
   }
+
   local newfile=''
   for file in *; do
     newfile=$(tr -s "$1" <<< "$file")
     mv "$file" "$newfile" 2>/dev/null
   done
+
   return 0
 }
 
@@ -346,12 +346,12 @@ mvs() {
 
 # Rename
 ren() {
-  [[ "$1" ]] || { echo "usage: rn 's/old/new/' *" >&2; return 1; }
+  [[ "$1" ]] || { echo 'usage: rn 's/old/new/' *' >&2; return 1; }
   local pattern="$1"; shift
-  [[ "$@" ]] || { echo "usage: rn 's/old/new/' *" >&2; return 1; }
+  [[ "$@" ]] || { echo 'usage: rn 's/old/new/' *' >&2; return 1; }
   local files="$@"
   rename -n "$pattern" $files
-  echo; read -p "Rename? [y/N]: " choice
+  echo; read -p 'Rename? [y/N]: ' choice
   [[ $choice =~ ^[yY] ]] && rename "$pattern" $files
 }
 
@@ -432,9 +432,11 @@ play() {
 # Open config file
 rc() {
   local files=(\
-    "$HOME/.bash_aliases" \
-    "$HOME/.bash_functions" \
     "$HOME/.bashrc" \
+    "$HOME/.config/bash/aliases" \
+    "$HOME/.config/bash/envs" \
+    "$HOME/.config/bash/functions" \
+    "$HOME/.config/bash/opts" \
     "$HOME/.config/bspwm/autostart" \
     "$HOME/.config/bspwm/config" \
     "$HOME/.config/bspwm/dunst/dunstrc" \
@@ -464,13 +466,6 @@ rc() {
 ssha() {
   eval "$(ssh-agent -s)"
   ssh-add -k
-}
-
-# Start starship
-starship() {
-  if type -P starship &> /dev/null; then
-    eval "$(starship init bash)"
-  fi
 }
 
 # alass sync
