Update bash functions

diff --git a/config/bash/functions b/config/bash/functions
--- a/config/bash/functions
+++ b/config/bash/functions
@@ -41,7 +41,11 @@ cuta() {
   local format="${file##*.}"
   local cutfile="$name-cut.$format"
 
-  ffmpeg -i "$file" -ss "$start" -t "$stop" -c copy "$cutfile" && \
+  ffmpeg \
+    -i "$file" \
+    -ss "$start" \
+    -t "$stop" \
+    -c copy "$cutfile" && \
     rm "$file" && \
     mv "$cutfile" "$file"
 }
@@ -54,18 +58,18 @@ ex() {
 
   case $1 in
     *.7z  ) 7z x $1       ;;
-    *.bz2 ) bunzip2 $1   ;;
-    *.deb ) ar x $1      ;;
+    *.bz2 ) bunzip2 $1    ;;
+    *.deb ) ar x $1       ;;
     *.gz  ) gunzip $1     ;;
-    *.rar ) unrar x $1   ;;
-    *.tar ) tar xf $1    ;;
-    *.tbz2) tar xjf $1  ;;
-    *.tgz ) tar xzf $1   ;;
+    *.rar ) unrar x $1    ;;
+    *.tar ) tar xf $1     ;;
+    *.tbz2) tar xjf $1    ;;
+    *.tgz ) tar xzf $1    ;;
     *.xz  ) tar xf $1     ;;
-    *.zip ) unzip $1     ;;
-    *.zst ) unzstd $1    ;;
+    *.zip ) unzip $1      ;;
+    *.zst ) unzstd $1     ;;
     *.Z   ) uncompress $1 ;;
-    *     ) echo "error: '$1' cannot be extracted" >&2 ;;
+    *     ) echo "error: format not compatible" >&2 ;;
   esac
 }
 
